### ISSUE TITLE
docker: command not found when use agent image with "-podman" suffix 

### ISSUE THREAD

**Issue by usernameisnull** [kubesphere/devops-agent#76]
when use "-podman" agent image, in jenkins pipeline, if I use sh 'docker ...' ,it said: `docker: command not found`
I think this stamement is not work 
https://github.com/kubesphere/devops-agent/blob/d7797562cce10d844ab146fc8c6be39024d94f18/base/podman/Dockerfile#L62

**Comment by LinuxSuRen** [comment]
Could you please tell us the exactly image name and tag?

**Comment by LinuxSuRen** [comment]
it was fixed in https://github.com/kubesphere/devops-agent/pull/68. You could use `ghcr.io/kubesphere/builder-base:v3.2.2-podman` instead.

See also:
```shell
[root@node1 ~]# docker run ghcr.io/kubesphere/builder-base:v3.2.2-podman docker
Error: missing command 'docker COMMAND'
Try 'docker --help' for more information.
```

**Comment by usernameisnull** [comment]
there is another problem:
I found that your other 3.2.2-podman images still have this problem，like：kubespheredev/builder-maven:v3.2.2-podman
you still use `alias` not `ln -s`
![image](https://user-images.githubusercontent.com/3390414/191885151-17ac2db4-8942-43a1-ba95-5fa60779977c.png)

**Comment by LinuxSuRen** [comment]
The alias does not work well in `kubespheredev/builder-maven:v3.2.2-podman` due to the following file

https://github.com/kubesphere/devops-agent/blob/d7797562cce10d844ab146fc8c6be39024d94f18/maven/podman/Dockerfile#L1

```shell
[root@node1 ~]# docker run kubespheredev/builder-base:v3.1.0-podman docker
Unable to find image 'kubespheredev/builder-base:v3.1.0-podman' locally
v3.1.0-podman: Pulling from kubespheredev/builder-base
2d473b07cdd5: Already exists
e65f63f3b9a3: Pull complete
454ff74a4e2c: Pull complete
66a2618fa589: Pull complete
ca3d576eed8b: Pull complete
c1afdb9dd30e: Pull complete
4433dd62b7ed: Pull complete
833077868859: Pull complete
674f640f3602: Pull complete
aa88434b7195: Pull complete
Digest: sha256:5e843645f3c07bbfcc191e93d879b41d1d73f09e5a9d4ecf9d1712c8d04c5467
Status: Downloaded newer image for kubespheredev/builder-base:v3.1.0-podman
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "docker": executable file not found in $PATH: unknown.
ERRO[0085] error waiting for container: context canceled
```

I think we should upgrade the base image. Please feel free to do it if you're interested in it.
